### ISSUE TITLE
SSL WebSocket client build error with MSVC and Boost 1.75

### ISSUE THREAD

**Issue by orikama** [boostorg/beast#2146]
Boost: 1.75.0
BOOST_BEAST_VERSION 301
Visual Studio 2019 16.8.3, Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64 (I guess version doesn't really matter as long as it's MSVC)

### Steps necessary to reproduce the problem
Just build ```websocket_client_async_ssl``` example with MSVC compiler and get this:
```
fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```
No errors using GCC or with Boost 1.74
A small research revealed that problem was introduced in ccd0f8822ae8532ea344658092bdb985915a946b. Applying this commit to Boost 1.74 gives the same error.

### Possible workarounds
- Add ```/bigobj``` flag as compiler suggests
- Or use ```BOOST_BEAST_SEPARATE_COMPILATION``` option and include ```boost/beast/src.hpp``` in a separate translation unit

Probably opening this issue is kinda useless since it's more of an MSVC problem, but I did it just to inform you, I guess ... :)

**Comment by madmongo1** [comment]
Thanks for reporting. I'll need to do some research on this as I've never seen this error before.

**Comment by madmongo1** [comment]
Aha
> x64 will have at least 4 sections associated with each function compiled /Gy or inlined from templates or class-inline: code, pdata, and debug info, and possibly xdata. X86 won’t have the pdata.

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1128?view=msvc-160

Looks like we need to update the test scripts.
