### ISSUE TITLE
Advanced server example issue

### ISSUE THREAD

**Issue by treebeard-66** [boostorg/beast#1047]
Hey There
 
I'm not sure if this is a bug but I'm totally stumped...

I've copied the advanced server example code and pasted it into visual studio 2015, linking against Boost 1.66 (BOOST_BEAST_VERSION 144) and this is the only code in the project.
http://www.boost.org/doc/libs/develop/libs/beast/example/advanced/server/advanced_server.cpp

I write socket client index.html file containing only the example code here: https://www.tutorialspoint.com/html5/html5_websocket.htm

And it connects and echos the message. I do nothing and then after ~5 seconds I get a read access violation in beast/websocket/impl/read.impl at line 323 ('goto loop'). 

Am I doing something stupid?

Cheers

**Comment by vinniefalco** [comment]
You don't seem to be doing anything wrong. I tried your scenario using the latest Visual Studio and Boost 1.66.0 and did not have a problem. I modified the **html5_websocket.htm** script to connect to `localhost:8080` (where my advanced server is running) and had no trouble.

Could you please try this in the latest Visual Studio to determine if the problem is Visual Studio 2015?

**Comment by carolinebeltran** [comment]
treebeard-66, I got the same behavior on **VC2015 32bit** & **VC2017 64bit**.  On **GCC 6.3 64bit**, it did not compile, but then I noticed that the link you sent appears to be an **older version of the demo**.  I tried this one:
http://www.boost.org/doc/libs/1_66_0/libs/beast/example/advanced/server/advanced_server.cpp

The new demo does not produce the access violation that you mentioned and appears to work just fine to me.

**Comment by vinniefalco** [comment]
> the link you sent appears to be an older version of the demo

This is the most recent version, and what will appear in the upcoming Boost 1.67.0 release:
https://github.com/boostorg/beast/blob/develop/example/advanced/server/advanced_server.cpp

This file should be the same as the one above
http://www.boost.org/doc/libs/develop/libs/beast/example/advanced/server/advanced_server.cpp

This is what is currently shipping in Boost 1.66.0:
http://www.boost.org/doc/libs/1_66_0/libs/beast/example/advanced/server/advanced_server.cpp

Are you saying that the 1.66.0 version succeeds, but the newer one fails?

**Comment by vinniefalco** [comment]
The tip of **develop** works correctly for me, I cannot reproduce this

**Comment by carolinebeltran** [comment]
Hello Vinnie, 

The link posted by treebeard-66 and the github link you posted are identical.  I had assumed that it was older code since I'm new here.  Nevertheless, with this demo, I experienced the same access violation as treebeard-66 when using **VC++ 2015 32bit** and **VC++ 2017 64bit**.  When using **GCC 6.3.0**, I get a compiler error.  These are the only 3 compilers that I have access to.

Please note that I am still on **Boost 1.66.0**, and that I have not updated any Boost library code.  This is the error produced by the **github version** on **GCC 6.3.0**:

`main.cpp:237:39: error: no matching function for call to ‘boost::beast::websocket::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::control_callback(std::_Bind_helper<false, void (websocket_session::*)(boost::beast::websocket::frame_type, boost::basic_string_view<char, std::char_traits<char> >), websocket_session*, const std::_Placeholder<1>&, const std::_Placeholder<2>&>::type)’`

**Comment by vinniefalco** [comment]
The advanced-server example has no file named main.cpp

**Comment by vinniefalco** [comment]
>This is the error produced by the github version on GCC 6.3.0:

The signature for `stream::control_callback` was changed after 1.66.0, so a newer advanced_server.cpp will not compile with the Beast from 1.66.0. MSVC allows lvalues to bind to non-const references as parameters, which is a Microsoft extension and explains why it compiles for you there.

**Comment by vinniefalco** [comment]
>Am I doing something stupid?

I think I figured it out. You are trying to use the newer version of advanced_server.cpp with the older version of Beast. And the control_callback function signature was changed, so a crash is likely. If you are using Boost 1.66.0, please use the advanced_server.cpp from the Boost 1.66.0 release, which can be found here:

https://github.com/boostorg/beast/blob/boost-1.66.0/example/advanced/server/advanced_server.cpp

Thanks!

**Comment by carolinebeltran** [comment]
> The advanced-server example has no file named main.cpp
Oh, I'm really sorry about causing confusion with the **main.cpp** error message.  I totally forgot to mention that I renamed the source file.  I do that because I have some blank 'Beast' template projects that I paste your demo code into in order to avoid setting any compiler options.  I'll keep that in mind from now on to avoid this.

**Comment by treebeard-66** [comment]
Hey sorry slow response was at trade show yesterday. 

I've got VS-2017 installed (with updates), built boost 1.66 with toolset=msvc-14.1 but got a build error now on the line:

`        ws_.control_callback(
            std::bind(
                &websocket_session::on_control_callback,
                this,
                std::placeholders::_1,
                std::placeholders::_2));
`
> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void boost::beast::websocket::stream<boost::asio::ip::tcp::socket>::control_callback(void)': cannot convert argument 1 from 'std::_Binder<std::_Unforced,void (__thiscall websocket_session::* )(boost::beast::websocket::frame_type,boost::beast::string_view),websocket_session *,const std::_Ph<1> &,const std::_Ph<2> &>' to 'std::_Binder<std::_Unforced,void (__thiscall websocket_session::* )(boost::beast::websocket::frame_type,boost::beast::string_view),websocket_session *,const std::_Ph<1> &,const std::_Ph<2> &> &'	websocket_server	c:\users\tom.cross\documents\visual studio 2017\projects\websocket_server\websocket_server\source.cpp	233	

I think these issues are a me problem. Any ideas would be greatly appreciated though.

**Comment by vinniefalco** [comment]
>I think these issues are a me problem. Any ideas would be greatly appreciated though.

As I said, the latest version of the advanced server example does not compile against Boost 1.66, as the signature for stream::control_callback has changed. If you want to compile the advanced-server example against Boost 1.66 then you need to use the version of the example which actually shipped in 1.66. That file can be obtained here:
http://www.boost.org/doc/libs/1_66_0/libs/beast/example/advanced/server/advanced_server.cpp

**Comment by treebeard-66** [comment]
Hey Vinnie. Yeah I deleted that message as saw the conversation i missed. Thanks, that works perfectly now. Can't believe I did that. Cheers mate
